### ISSUE TITLE
automatically adding types

### ISSUE THREAD

**Issue by kablamo** [ka2u/Net-Amazon-DynamoDB-Lite#2]
Net::Amazon::DynamoDB::Lite automatically removes types from the data returned by `get()` and `scan()`.  Is there a reason you don't automatically add types in `put()`?  

I wrote a module which does that.  Is it a bad idea?  It uses your module underneath.  I would love any feedback you are interested in giving.

https://github.com/kablamo/Net-Amazon-DynamoDB-Table

**Comment by ka2u** [comment]
Thank you for your feedback.

The judgment of the type was sometimes difficult in Perl as a reason, and I gave up putting the type automatically in case of `put()`. For example ID, 12345 is usually a character string, but it has been sometimes handled in Int.

```
[kaz@] $ plenv exec carton exec perl -MScalar::Util -e 'print Scalar::Util::looks_like_number 12345'
1
[kaz@] $ plenv exec carton exec perl -MScalar::Util -e 'print Scalar::Util::looks_like_number "12345"'
1
```

The `get()`  and  `put()` returns what kind of type is it, you can remove simply because it isn't necessary to judge the type.

I'm sorry, but I can't take the module you made in by a reason above-mentioned.

**Comment by kablamo** [comment]
You are right!  Thanks for noticing that.  

But today I fixed that bug.  
Here is the fix:  https://github.com/kablamo/Net-Amazon-DynamoDB-Table/commit/948487d7df87a0f183847e8e4de301ea1795b716
Here a test for the fix: https://github.com/kablamo/Net-Amazon-DynamoDB-Table/commit/355cb8de220995f3f3b3d9b64e4dbc847ed1d5b3

I stole this fix from Mojo::JSON.

**Comment by kablamo** [comment]
FYI, I just released this module to cpan.  Thanks for your help with it! 
https://metacpan.org/pod/Net::Amazon::DynamoDB::Table

**Comment by ka2u** [comment]
It's a good release!
